CREATE TABLE USERS
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    GUID       UUID        default Random_uuid() NOT NULL UNIQUE, -- using int as primary key for better search
    USERNAME   VARCHAR(50) UNIQUE                NOT NULL,
    PASSWORD   VARCHAR(255) UNIQUE               NOT NULL,
    NAME       VARCHAR(255)                      NOT NULL,
    EMAIL      VARCHAR(64),
    ROLE       VARCHAR(10) DEFAULT 'USER'        NOT NULL,
    CREATED_AT DATE        DEFAULT CURRENT_DATE  NOT NULL
);



CREATE TABLE TASK_TYPE
(
    ID        INT PRIMARY KEY AUTO_INCREMENT,
    TYPE_NAME VARCHAR(50) NOT NULL,
    SVG       CLOB        NOT NULL
);

-- to keep track of the max number for id (prefix-number)
CREATE TABLE ID_TRACK
(
    PREFIX     VARCHAR(50) NOT NULL UNIQUE,
    MAX_NUMBER INT         NOT NULL
);

CREATE TABLE COMMENTS
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    CONTENT    CLOB NOT NULL,
    AUTHOR     UUID NOT NULL,
    TASK_ID    UUID NOT NULL,
    STATUS     VARCHAR(50) DEFAULT 'DRAFT',
    CREATED_AT DATE        DEFAULT CURRENT_DATE
);

CREATE TABLE BOARDS
(
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    NAME        VARCHAR(255) NOT NULL,
    DESCRIPTION CLOB
);

CREATE TABLE BOARD_COLUMNS
(
    BOARD_ID   INT         NOT NULL,
    NAME       VARCHAR(50) NOT NULL,
    SORT_INDEX INT         NOT NULL
);

CREATE TABLE PROJECTS
(
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    GUID        UUID         NOT NULL UNIQUE,
    NAME        VARCHAR(255) NOT NULL,
    SHORT_NAME  VARCHAR(20)  NOT NULL UNIQUE,
    TYPE        VARCHAR(255),
    DESCRIPTION CLOB,
    CREATED_AT  DATE DEFAULT CURRENT_DATE,
    OWNER_ID    UUID         NOT NULL
);

CREATE TABLE PROJECT_MEMBERS
(
    USER_ID    UUID NOT NULL,
    PROJECT_ID INT  NOT NULL
);

CREATE TABLE TASKS
(
    ID               VARCHAR(255) PRIMARY KEY,
    TITLE            VARCHAR(255) NOT NULL,
    DESCRIPTION      CLOB         NOT NULL,
    STATUS           VARCHAR(50)  NOT NULL,
    TASK_TYPE_ID     INT          NOT NULL,
    PRIORITY         VARCHAR(50)  NOT NULL,
    STORY_POINTS     NUMERIC(2, 1),
    ESTIMATE_DAYS    INT,
    ESTIMATE_MINUTES INT,
    PARENT_ID        VARCHAR(255),
    PROJECT_ID       UUID         NOT NULL,
    CREATED_BY       UUID         NOT NULL,
    CREATED_AT       DATE DEFAULT CURRENT_DATE,

    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (GUID)
);
