CREATE TABLE USERS
(
    ID         SERIAL PRIMARY KEY,
    GUID       UUID        DEFAULT gen_random_uuid() NOT NULL UNIQUE, -- using int as primary key for better searcH
    USERNAME   VARCHAR(50) UNIQUE                    NOT NULL,
    PASSWORD   VARCHAR(255) UNIQUE                   NOT NULL,
    NAME       VARCHAR(255)                          NOT NULL,
    EMAIL      VARCHAR(64),
    ROLE       VARCHAR(10) DEFAULT 'USER'            NOT NULL,
    CREATED_AT DATE        DEFAULT CURRENT_DATE      NOT NULL
);

CREATE TABLE PROJECTS
(
    ID          SERIAL PRIMARY KEY,
    GUID        UUID         NOT NULL UNIQUE,
    NAME        VARCHAR(255) NOT NULL,
    SHORT_NAME  VARCHAR(20)  NOT NULL,
    TYPE        VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT, --DONT THINK WE NEED THIS
    CREATED_AT  DATE DEFAULT CURRENT_DATE,
    OWNER_ID    UUID         NOT NULL
);

CREATE TABLE TASKS
(
    ID               VARCHAR(255) NOT NULL PRIMARY KEY UNIQUE,
    TITLE            VARCHAR(255) NOT NULL,
    DESCRIPTION      TEXT         NOT NULL,
    STATUS           VARCHAR(50)  NOT NULL,
    TASK_TYPE_ID     INT          NOT NULL,
    PRIORITY         VARCHAR(50)  NOT NULL,
    STORY_POINTS     NUMERIC(2, 1),
    ESTIMATE_DAYS    INT,
    ESTIMATE_MINUTES INT,
    PARENT_ID        VARCHAR(255),
    PROJECT_ID       UUID         NOT NULL,
    CREATED_BY       UUID         NOT NULL,
    CREATED_AT       DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (GUID)
);

CREATE TABLE TASK_TYPE
(
    ID        SERIAL PRIMARY KEY,
    TYPE_NAME VARCHAR(50) NOT NULL,
    SVG       TEXT        NOT NULL
);

-- to keep track of the max number for id (prefix-number)
CREATE TABLE ID_TRACK
(
    PREFIX     VARCHAR(50) NOT NULL UNIQUE,
    MAX_NUMBER INT         NOT NULL
);

CREATE TABLE COMMENTS
(
    ID         SERIAL PRIMARY KEY,
    CONTENT    TEXT NOT NULL,
    AUTHOR     UUID NOT NULL,
    TASK_ID    UUID NOT NULL,
    STATUS     VARCHAR(50) DEFAULT 'DRAFT',
    CREATED_AT DATE        DEFAULT CURRENT_DATE
);

CREATE TABLE BOARDS
(
    ID          SERIAL PRIMARY KEY,
    NAME        VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT
);

CREATE TABLE BOARD_COLUMNS
(
    BOARD_ID   SERIAL      NOT NULL,
    NAME       VARCHAR(50) NOT NULL,
    SORT_INDEX INT         NOT NULL
);


CREATE TABLE PROJECT_MEMBERS
(
    USER_ID    UUID    NOT NULL,
    PROJECT_ID INTEGER NOT NULL
);